import streamlit as st

st.title("Hello, Streamlit!")
st.write("This is a simple web application using Streamlit.")
st.button("Click me!")

st.text_area("Your feedback", "Type your feedback here...")
st.slider("Select a value", 0, 100, 50)
st.checkbox("I agree to the terms and conditions")  
st.selectbox("Choose an option", ["Option 1", "Option 2", "Option 3"])
st.date_input("Select a date")
st.file_uploader("Upload a file")
st.color_picker("Pick a color")
st.progress(70)
st.map()
st.balloons()
st.sidebar.title("Sidebar")
st.sidebar.button("Sidebar Button") 
st.sidebar.selectbox("Sidebar Selectbox", ["A", "B", "C"])
st.sidebar.slider("Sidebar Slider", 0, 10, 5)   
st.sidebar.checkbox("Sidebar Checkbox")
st.sidebar.text_input("Sidebar Text Input", "Type here...")
st.sidebar.date_input("Sidebar Date Input")
st.image("https://via.placeholder.com/150", caption="Sample Image")
st.video("https://www.w3schools.com/html/mov_bbb.mp4")
st.audio("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3")
st.code("print('Hello, World!')", language='python')
st.latex(r"E=mc^2")
st.json({"name": "John", "age": 30, "city": "New York"})
st.table({"Column 1": [1, 2, 3], "Column 2": ["A", "B", "C"]})
st.dataframe({"Column 1": [1, 2, 3], "Column 2": ["A", "B", "C"]})
st.metric("Temperature", "70 °F", "+1.2 °F")